security:

    encoders:
          Xelbot\UserBundle\Entity\User: bcrypt

    role_hierarchy:
            ROLE_ADMIN: ROLE_USER

    providers:
        user_db:
            entity:
                class: Xelbot\UserBundle\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: user_db
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week
            logout: true
            anonymous: true

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, roles: ROLE_ADMIN }

