<?php

namespace Xelbot\AppBundle\Entity\Repository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends \Doctrine\ORM\EntityRepository
{
}
